// src/utils/UBSFJoinville.js

const listaBruta = [
  "UBSF ULYSSES GUIMARAES",
  "UBSF LAGOINHA",
  "UBSF DOM GREGORIO",
  "UBSF ESTRADA ANABURGO",
  "UBSF DA ILHA",
  "UBSF ADHEMAR GARCIA PEDRO CELESTINO DA SILVA JUNIOR",
  "UBSF RIO DA PRATA ADALBERTO LARSEN",
  "UBSF SAO MARCOS",
  "UBSF AVENTUREIRO I",
  "UBSF ESTEVAO DE MATOS",
  "UBSF BAKHITA",
  "UBSF NOVA BRASILIA",
  "UBSF BOM RETIRO",
  "UBSF PROFIPO",
  "UBSF ITAUM",
  "UBSF PARANAGUAMIRIM",
  "UBSF PARQUE JOINVILLE",
  "UBSF VILA NOVA",
  "UBSF BUCAREIN",
  "UBSF ITINGA",
  "UBSF FLORESTA",
  "UBSF SAGUACU",
  "UBSF JOAO COSTA",
  "UBSF MORRO DO AMARAL",
  "UBSF JARDIM SOFIA",
  "UBSF EDLA JORDAN",
  "UBSF PARQUE DOUAT",
  "UBSF COSTA E SILVA",
  "UBSF VILA NOVA RURAL",
  "UBSF JARIVATUBA BELQUISE ANA QUINTERO",
  "UBSF FATIMA",
  "UBSF COMASA",
  "UBSF AVENTUREIRO III",
  "UBSF VILA NOVA I DAGOBERTO JOSE DE CAMPOS",
  "UBSF GLORIA SERGIO DUPRAT",
  "UBSF AVENTUREIRO II",
  "UBSF BOEHMERWALD",
  "UBSF JARDIM EDILENE",
  "UBSF CANELA",
  "UBSF MORRO DO MEIO",
  "UBSF WILLY SCHOSSLAND",
  "UBSF RIO BONITO",
  "UBSF PARQUE GUARANI ARVELINA COTTA RODRIGUES",
  "UBSF LEONARDO SCHILICKMANN",
  "UBSF KM 4",
  "UBSF CUBATAO",
  "UBSF CAIC VILA PARANAENSE",
  "UBSF MOINHO DOS VENTOS",
  "UBSF PIRABEIRABA OSMAR DALONSO",
  "UBSF JATIVOCA",
  "UBSF JARDIM PARAISO SERVIDORA ERLIETE ADIR DOS SANTOS",
  "UBSF JARDIM PARAISO CANTO DO RIO"
];

// Função para remover acentos e deixar tudo maiúsculo
const formatarNomeUBSF = (nome) => {
  return nome
    .normalize("NFD") 
    .replace(/[\u0300-\u036f]/g, "") 
    .toUpperCase();
};

// Mapeia, formata e ordena alfabeticamente (A-Z)
export const ubsfJoinville = listaBruta
  .map(formatarNomeUBSF)
  .sort((a, b) => a.localeCompare(b));